//! Consumer dispatch: Node.js → IPC.
//!
//! Lets JavaScript call methods of remote IPC services through the generic
//! `callService(service, method, args)` and `callServiceStream(...)` APIs.
//!
//! # Where the `(service, method)` surface comes from
//!
//! The methods are **generated by `#[service]`**: this module declares no method
//! table of its own, it invokes the single JSON view the macro emits for each
//! service. The *services* are the ones
//! [`crate::services::maintained_services!`] names, so the consumer side and the
//! provider side cannot disagree about which names exist — the defect this module
//! used to have was a hardcoded table that had already lost `ContextService`
//! while the service was advertised.
//!
//! # Call flow
//!
//! 1. JS: `await gateway.callService('DatabaseService', 'get_user_age', 'Alice')`
//! 2. N-API → [`call_ipc_method`] → the generated `JsonInvoker::invoke_json`
//! 3. Proxy retrieval through [`ice_rpc::ServiceLocator::get`]
//! 4. Business call (IPC to the remote provider)
//! 5. The [`JsonOutcome`] of the call: one value (`ReadMode::First`) or every
//!    value (`ReadMode::All`)
//!
//! The reading mode is an **argument**, not a second generated entry point: the
//! two JavaScript functions share one dispatch table, so a method added to a
//! service is served by both without touching this file.

use crate::error::{GatewayError, GatewayErrorCode};
use crate::services;
use ice_rpc::gen::{JsonCallError, JsonInvoker, JsonOutcome, ReadMode};
use ice_rpc::ServiceLocator;
use serde_json::Value;

/// Dispatch arm over the services this gateway maintains.
///
/// Invoked through [`crate::services::maintained_services!`], which expands to
/// `dispatch_one_consumer!(service, method, args, read, ProxyA, ProxyB, …)`; `read`
/// is the reading policy forwarded to the generated JSON view.
macro_rules! dispatch_one_consumer {
    ($service:expr, $method:expr, $args:expr, $read:expr, $($proxy:ty),* $(,)?) => {
        match $service {
            $( <$proxy>::SERVICE_NAME => {
                let proxy = ServiceLocator::global()
                    .get::<$proxy>()
                    .await
                    .ok_or_else(|| no_provider($service))?;
                // `None` means "this service has no such method": the JSON view
                // answers `Some` even when the call itself fails, so the two
                // cases stay distinguishable.
                match proxy.invoke_json($method, $args, $read).await {
                    Some(result) => result.map_err(call_error),
                    None => Err(unknown_method($service, $method)),
                }
            })*
            _ => Err(unknown_service($service)),
        }
    };
}

/// Calls a method of a remote IPC service and returns its first value as JSON.
///
/// Answers as soon as the first value is available, which is the only mode able
/// to serve a service that streams without ever completing.
///
/// # Errors
/// `E_UNKNOWN_SERVICE`, `E_UNKNOWN_METHOD`, `E_INVALID_ARGS`, `E_NO_PROVIDER`,
/// `E_TRANSPORT`, or `E_BUSINESS` when the service failed **or completed without
/// emitting any value** — a bare `null` could not be told apart from a real
/// `null` payload. See [`GatewayErrorCode`].
pub async fn call_ipc_method(
    service: &str,
    method: &str,
    args: Value,
) -> Result<Value, GatewayError> {
    let read = ReadMode::First;
    let outcome =
        services::maintained_services!(dispatch_one_consumer, service, method, args, read);
    match outcome? {
        JsonOutcome::Value(value) => Ok(value),
        JsonOutcome::Nothing => Err(no_value(service, method)),
    }
}

/// Calls a method of a remote IPC service and returns **every** value it emits.
///
/// The multi-value counterpart of [`call_ipc_method`], for a service whose
/// method streams several values before completing: it waits for the terminal
/// event instead of returning the first value. An empty stream is a legitimate
/// empty result here, whereas [`call_ipc_method`] has to report a missing value.
pub async fn call_ipc_method_stream(
    service: &str,
    method: &str,
    args: Value,
) -> Result<Vec<Value>, GatewayError> {
    let read = ReadMode::All;
    let outcome =
        services::maintained_services!(dispatch_one_consumer, service, method, args, read);
    match outcome? {
        // `ReadMode::All` answers with the array of every value. A lone value is
        // wrapped rather than dropped, so a deviation shows up in the result
        // instead of being silently swallowed.
        JsonOutcome::Value(Value::Array(values)) => Ok(values),
        JsonOutcome::Value(other) => Ok(vec![other]),
        JsonOutcome::Nothing => Ok(Vec::new()),
    }
}

/// Maps the failure reported by the generated JSON view onto the gateway codes.
///
/// Keeping the mapping here is what lets the generated code stay free of any
/// `gateway_nodejs` type: [`JsonInvoker`] reports a [`JsonCallError`], the
/// gateway owns the stable codes.
fn call_error(error: JsonCallError) -> GatewayError {
    let (code, message) = match error {
        JsonCallError::InvalidArgs(message) => (GatewayErrorCode::InvalidArgs, message),
        JsonCallError::Business(message) => (GatewayErrorCode::Business, message),
        JsonCallError::Transport(message) => (GatewayErrorCode::Transport, message),
    };
    GatewayError::new(code, message)
}

/// Builds the `E_BUSINESS` failure of a single-value call that emitted nothing.
///
/// The call itself succeeded — the service simply completed without a value. A
/// `null` answer would be indistinguishable from a real `null` payload, which is
/// why the absence is reported as a failure on the single-value entry point.
fn no_value(service: &str, method: &str) -> GatewayError {
    GatewayError::new(
        GatewayErrorCode::Business,
        format!("'{service}.{method}' completed without emitting a value"),
    )
}

/// Builds the `E_NO_PROVIDER` failure for a service nobody advertises.
fn no_provider(service: &str) -> GatewayError {
    GatewayError::new(
        GatewayErrorCode::NoProvider,
        format!("no provider is connected for '{service}'"),
    )
}

/// Builds the `E_UNKNOWN_METHOD` failure of a known service.
fn unknown_method(service: &str, method: &str) -> GatewayError {
    GatewayError::new(
        GatewayErrorCode::UnknownMethod,
        format!("'{service}' has no method '{method}'"),
    )
}

/// Builds the `E_UNKNOWN_SERVICE` failure, listing what the gateway can serve.
fn unknown_service(service: &str) -> GatewayError {
    GatewayError::new(
        GatewayErrorCode::UnknownService,
        format!(
            "unknown service '{service}'; known services: {}",
            services::known_service_names().join(", ")
        ),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_unknown_service_lists_the_served_ones() {
        let error = unknown_service("NoSuchService");
        assert_eq!(error.code(), GatewayErrorCode::UnknownService);
        assert!(error.message().contains("NoSuchService"));
        for name in services::known_service_names() {
            assert!(
                error.message().contains(name),
                "the message must list '{name}': {}",
                error.message()
            );
        }
    }

    #[test]
    fn an_unknown_method_names_the_service_and_the_method() {
        let error = unknown_method("ContextService", "nope");
        assert_eq!(error.code(), GatewayErrorCode::UnknownMethod);
        assert!(error.message().contains("ContextService"));
        assert!(error.message().contains("nope"));
    }

    #[test]
    fn a_missing_provider_is_reported_on_its_own_code() {
        let error = no_provider("DatabaseService");
        assert_eq!(error.code(), GatewayErrorCode::NoProvider);
        assert!(error.message().contains("DatabaseService"));
    }

    #[test]
    fn every_generated_failure_kind_maps_to_a_code() {
        let cases = [
            (
                JsonCallError::InvalidArgs("boom".to_string()),
                GatewayErrorCode::InvalidArgs,
            ),
            (
                JsonCallError::Business("boom".to_string()),
                GatewayErrorCode::Business,
            ),
            (
                JsonCallError::Transport("boom".to_string()),
                GatewayErrorCode::Transport,
            ),
        ];
        for (error, expected) in cases {
            let mapped = call_error(error);
            assert_eq!(mapped.code(), expected);
            assert_eq!(mapped.message(), "boom");
        }
    }

    #[test]
    fn a_completion_without_a_value_is_a_business_failure() {
        let error = no_value("ContextService", "watch");
        assert_eq!(error.code(), GatewayErrorCode::Business);
        assert!(error.message().contains("ContextService.watch"));
    }
}
