//! N-API entry point for the ice-rpc Node.js gateway.
//!
//! # Architecture
//!
//! - A shared iceoryx2 Node (via [`ice_rpc::locator()`])
//! - A `NodeJsBridge` singleton (agnostic, generic)
//! - Service proxies in `ProviderNodeJs` mode (generated by the `#[service]` macro)
//!
//! # Node.js API
//!
//! ```javascript
//! const gw = require('gateway-nodejs');
//!
//! // Register only the services that THIS process implements.
//! // Consumers are created automatically on demand via locator().get().
//! gw.registerService('ContextService');    // ← this process is the Provider of ContextService
//! gw.init((call) => { ... });             // ← dispatcher callback
//! gw.shutdown();
//! ```
//!
//! # Lazy proxies
//!
//! [`init`] calls `ice_rpc::init_without_ctrl_c()`. No global registry
//! is needed: `ice_rpc::locator().get()` instantiates any
//! proxy on demand, from its type.

mod consumer;
mod nodejs_bridge;
mod runtime;
mod services;

use napi::bindgen_prelude::{Function, Unknown};
use napi_derive::napi;

/// Registers a Node.js Provider service by its logical name.
///
/// To call BEFORE [`init`].
///
/// # JS signature
/// `registerService(serviceName: string): boolean`
///
/// # Supported values
/// `"ContextService"`, `"DatabaseService"`, `"ConfigService"`, `"HttpService"`
///
/// # Returns
/// `true` if the service was registered successfully.
#[napi]
pub fn register_service(service_name: String) -> bool {
    let _ = runtime::init_runtime();
    services::register_service(&service_name)
}

/// Initializes the gateway: iceoryx2 Node, Node.js bridge, consumer factory,
/// discovery, dispatch loop, and starts `initialize_all()` in the background.
///
/// The **Provider** services must have been registered beforehand via
/// [`register_service`]. Any other proxy is available automatically
/// after `init()` via [`ice_rpc::ServiceLocator::get`], without registration.
///
/// # JS signature
/// `init(callback: (call: { correlationId, service, method, args }) => void): boolean`
///
/// # Arguments
/// * `callback` — JS function called on each incoming IPC request.
///
/// # Returns
/// `true` if the initialization succeeded.
#[napi]
pub fn init(callback: Function<'_, serde_json::Value, Unknown<'static>>) -> bool {
    log::info!("Initializing the NodeJS gateway...");

    let _ = runtime::init_runtime();

    if nodejs_bridge::NodeJsBridge::init(callback).is_err() {
        log::error!("Failed to initialize the NodeJsBridge.");
        return false;
    }

    ice_rpc::nodejs_dispatch::set_dispatch(|cid, service, method, args| {
        runtime::block_on(nodejs_bridge::NodeJsBridge::global().call_async(cid, service, method, args))
    });

    ice_rpc::init_without_ctrl_c();

    match ice_rpc::locator().get_node_sync() {
        Ok(node) => {
            log::info!(
                "iceoryx2 Node created (pid={}, strong_count={}).",
                std::process::id(),
                std::sync::Arc::strong_count(&node)
            );
        }
        Err(e) => {
            log::error!("Failed to create the iceoryx2 Node: {:?}", e);
            return false;
        }
    }

    {
        runtime::block_on(async {
            ice_rpc::locator().start_discovery();
            ice_rpc::locator().start_dispatch_if_needed();
        });
    }

    services::start_initialize_all();

    log::info!("NodeJS gateway ready.");
    true
}

/// Calls a method of a remote IPC service from Node.js.
///
/// The call is executed synchronously on the current thread through the
/// runtime-agnostic executor provided by `ice_rpc::rt` (no Tokio runtime).
///
/// # JS signature
/// `callService(serviceName: string, methodName: string, args: any): any`
///
/// # Example
/// ```javascript
/// const age = gateway.callService('DatabaseService', 'get_user_age', 'Alice');
/// console.log(`Alice is ${age} years old`);
/// ```
///
/// # Supported services
/// - `DatabaseService` : `get_user_age(name)`, `get_person({ nom, prenom })`
/// - `ConfigService` : `get(key)`
/// - `HttpService` : `send_request({ method, url, headers, body })`
///
/// # Returns
/// The return value (first `Next` event). On failure, an N-API error is
/// raised and can be caught from JavaScript as an exception.
#[napi]
pub fn call_service(
    service_name: String,
    method_name: String,
    args: serde_json::Value,
) -> napi::Result<serde_json::Value> {
    runtime::block_on(consumer::call_ipc_method(&service_name, &method_name, args))
        .map_err(napi::Error::from_reason)
}

/// Stops the gateway: releases the IPC resources and the Tokio runtime.
#[napi]
pub fn shutdown() {
    log::info!("Stopping the gateway...");
    let _ = runtime::spawn_task(async move {
        ice_rpc::shutdown_and_release().await;
        log::info!("IPC resources released.");
    });
    runtime::shutdown_runtime();
    log::info!("Gateway stopped.");
}

/// Resolves a pending Node.js call.
///
/// # JS signature
/// `resolveNodeJsCall(correlationId: string, result: any): void`
#[napi]
pub fn resolve_nodejs_call(
    correlation_id_hex: String,
    result: serde_json::Value,
) -> napi::Result<()> {
    if nodejs_bridge::resolve_call(correlation_id_hex, result) {
        Ok(())
    } else {
        Err(napi::Error::from_reason(
            "Correlation ID not found (expired or nonexistent)".to_string(),
        ))
    }
}

/// Returns the gateway version.
#[napi]
pub fn version() -> String {
    format!(
        "gateway-nodejs v{} (ice-rpc v{}, iceoryx2 v{})",
        env!("CARGO_PKG_VERSION"),
        "0.1.0",
        "0.9"
    )
}
