//! N-API entry point for the ice-rpc Node.js gateway.
//!
//! # Architecture
//!
//! - A shared iceoryx2 Node (via [`ice_rpc::locator()`])
//! - A `NodeJsBridge` singleton (agnostic, generic)
//! - Service proxies in `ProviderNodeJs` mode (generated by the `#[service]` macro)
//!
//! # Node.js API
//!
//! ```javascript
//! const gw = require('gateway-nodejs');
//!
//! // Register only the services that THIS process implements.
//! // Consumers are created automatically on demand via locator().get().
//! gw.registerService('ContextService');    // ← this process is the Provider of ContextService
//! gw.init((call) => { ... });             // ← dispatcher callback
//! gw.shutdown();
//! ```
//!
//! # Lazy proxies
//!
//! [`init`] calls `ice_rpc::gen::init_without_ctrl_c()`. No global registry
//! is needed: `ice_rpc::locator().get()` instantiates any
//! proxy on demand, from its type.

#![cfg_attr(test, allow(clippy::unwrap_used))] // test code may panic; production libs keep the deny, see [workspace.lints]
mod consumer;
mod nodejs_bridge;
mod runtime;
mod services;

use napi::bindgen_prelude::{Function, Unknown};
use napi_derive::napi;

/// Keeps the ice-rpc shutdown guard alive for the whole gateway lifetime.
///
/// The N-API entry points (`init` / `shutdown`) are free functions, so there is
/// no long-lived owner to hold the guard: it is stored here instead. Dropping
/// it would cancel the global tokens immediately, which must not happen while
/// the gateway is running.
static SHUTDOWN_GUARD: std::sync::OnceLock<ice_rpc::gen::ShutdownGuard> =
    std::sync::OnceLock::new();

/// Registers a Node.js Provider service by its logical name.
///
/// To call BEFORE [`init`].
///
/// # JS signature
/// `registerService(serviceName: string): boolean`
///
/// # Supported values
///
/// Every service listed in `common::with_nodejs_providers!` — currently
/// `"ConfigService"`, `"ContextService"`, `"DatabaseService"`, `"HttpService"`
/// and `"NotificationService"`. That inventory lives in the `common` crate,
/// next to the `#[service]` declarations, so the Node.js surface cannot drift
/// from them (the `nodejs_provider_inventory_is_exhaustive` test enforces it).
///
/// # Returns
/// `true` if the service was registered successfully.
#[napi]
pub fn register_service(service_name: String) -> bool {
    let _ = runtime::init_runtime();
    services::register_service(&service_name)
}

/// Initializes the gateway: iceoryx2 Node, Node.js bridge, consumer factory,
/// discovery, dispatch loop, and starts `initialize_all()` in the background.
///
/// The **Provider** services must have been registered beforehand via
/// [`register_service`]. Any other proxy is available automatically
/// after `init()` via [`ice_rpc::ServiceLocator::get`], without registration.
///
/// # JS signature
/// `init(callback: (call: { correlationId, service, method, args }) => void): boolean`
///
/// # Arguments
/// * `callback` — JS function called on each incoming IPC request.
///
/// # Returns
/// `true` if the initialization succeeded.
#[napi]
pub fn init(callback: Function<'_, serde_json::Value, Unknown<'static>>) -> bool {
    log::info!("Initializing the NodeJS gateway...");

    let _ = runtime::init_runtime();

    if nodejs_bridge::NodeJsBridge::init(callback).is_err() {
        log::error!("Failed to initialize the NodeJsBridge.");
        return false;
    }

    ice_rpc::nodejs_dispatch::set_dispatch(|cid, service, method, args| {
        runtime::block_on(
            nodejs_bridge::NodeJsBridge::global().call_async(cid, service, method, args),
        )
    });

    // `init_without_ctrl_c` returns the RAII guard; it must be kept alive for
    // the whole gateway lifetime, hence the process-wide storage.
    let _ = SHUTDOWN_GUARD.set(ice_rpc::gen::init_without_ctrl_c());

    // The native request/response transport creates its own shared iceoryx2
    // node lazily, on the first client call or service start (`initialize_all`
    // below). No explicit node bootstrapping or dispatch loop is needed.
    log::info!(
        "iceoryx2 native transport ready (pid={}).",
        std::process::id()
    );

    services::start_initialize_all();

    log::info!("NodeJS gateway ready.");
    true
}

/// Calls a method of a remote IPC service from Node.js.
///
/// The call is executed synchronously on the current thread through the
/// runtime-agnostic executor provided by `ice_rpc::rt` (no Tokio runtime).
///
/// # JS signature
/// `callService(serviceName: string, methodName: string, args: any): any`
///
/// # Example
/// ```javascript
/// const age = gateway.callService('DatabaseService', 'get_user_age', 'Alice');
/// console.log(`Alice is ${age} years old`);
/// ```
///
/// # Supported services
/// - `DatabaseService` : `get_user_age(name)`, `get_person({ nom, prenom })`
/// - `ConfigService` : `get(key)`
/// - `HttpService` : `send_request({ method, url, headers, body })`
///
/// # Returns
/// The return value (first `Next` event). On failure, an N-API error is
/// raised and can be caught from JavaScript as an exception.
#[napi]
pub fn call_service(
    service_name: String,
    method_name: String,
    args: serde_json::Value,
) -> napi::Result<serde_json::Value> {
    runtime::block_on(consumer::call_ipc_method(&service_name, &method_name, args))
        .map_err(napi::Error::from_reason)
}

/// Stops the gateway: releases the IPC resources and the Tokio runtime.
#[napi]
pub fn shutdown() {
    log::info!("Stopping the gateway...");
    let _ = runtime::spawn_task(async move {
        ice_rpc::gen::shutdown_and_release().await;
        log::info!("IPC resources released.");
    });
    runtime::shutdown_runtime();
    log::info!("Gateway stopped.");
}

/// Resolves a pending Node.js call.
///
/// # JS signature
/// `resolveNodeJsCall(correlationId: string, result: any): void`
#[napi]
pub fn resolve_nodejs_call(
    correlation_id_hex: String,
    result: serde_json::Value,
) -> napi::Result<()> {
    if nodejs_bridge::resolve_call(correlation_id_hex, result) {
        Ok(())
    } else {
        Err(napi::Error::from_reason(
            "Correlation ID not found (expired or nonexistent)".to_string(),
        ))
    }
}

/// Returns the gateway version.
#[napi]
pub fn version() -> String {
    format!(
        "gateway-nodejs v{} (ice-rpc v{}, iceoryx2 v{})",
        env!("CARGO_PKG_VERSION"),
        "0.1.0",
        "0.9"
    )
}
