//! Registration of the Node.js services (Providers).
//!
//! Only the services this Node.js process **implements** (Provider mode) are
//! registered here. The consumers are created on demand by
//! [`ice_rpc::ServiceLocator::get`], from their type: nothing to declare.
//!
//! # Initialization flow
//!
//! 1. JS: `gateway.registerService("ContextService")` → [`register_service`]
//!    → `ContextServiceProxy::provide_json()` → `ServiceLocator::register()`.
//! 2. JS: `gateway.init(callback)` → the bridge and the dispatch loop.
//! 3. [`spawn_initialize_all`]: `ServiceLifecycle::init()` on each provider.
//!
//! # The list of maintained services
//!
//! [`maintained_services!`] below names the proxies this gateway advertises, and
//! it is the **only** list: [`register_service`], [`known_service_names`] and the
//! consumer dispatch all read it. It is deliberately the gateway's own — a
//! process that maintains a subset of what `common` declares should say which
//! subset, here, rather than rely on a shared crate keeping a matching inventory.
//!
//! Adding a service is one line below, and the compiler checks it: a name that
//! does not match a proxy generated by `#[service]` fails to build.

use crate::error::{GatewayError, GatewayErrorCode};
use crate::state::Phase;

/// The services this gateway maintains — its own hard-coded list.
///
/// One entry per proxy generated by `#[service]`; `<Proxy>::SERVICE_NAME` is the
/// logical name a JS caller passes to `registerService()`. Each of the three
/// users needs the proxy as a **type** — `provide_json()`, `invoke_json` and
/// `ServiceLocator::get::<Proxy>()` are all instantiated per proxy — which is why
/// the list is spelled as a macro argument vector rather than a `const` array of
/// name strings.
macro_rules! maintained_services {
    ($callback:ident $(, $arg:expr)* $(,)?) => {
        $callback!(
            $($arg,)*
            common::ConfigServiceProxy,
            common::ContextServiceProxy,
            common::DatabaseServiceProxy,
            common::HttpServiceProxy,
            common::NotificationServiceProxy,
        )
    };
}
pub(crate) use maintained_services;

/// Dispatch arm for a single provider proxy.
///
/// Invoked through [`maintained_services!`], which expands to
/// `register_one_provider!(service_name, ProxyA, ProxyB, …)`.
macro_rules! register_one_provider {
    ($service_name:expr, $($proxy:ty),* $(,)?) => {
        match $service_name {
            $( <$proxy>::SERVICE_NAME => {
                let proxy = <$proxy>::provide_json();
                ice_rpc::rt::block_on(async move {
                    ice_rpc::locator().register(proxy).await;
                });
                Ok(())
            })*
            _ => Err(unknown_service_error($service_name)),
        }
    };
}

/// Builds the `E_UNKNOWN_SERVICE` failure, listing the advertisement surface.
fn unknown_service_error(service_name: &str) -> GatewayError {
    GatewayError::new(
        GatewayErrorCode::UnknownService,
        format!(
            "unknown service '{}'; known services: {}",
            service_name,
            known_service_names().join(", ")
        ),
    )
}

/// The logical names this gateway can advertise, sorted and deduplicated.
///
/// Read from [`maintained_services!`], so the advertisement surface and the
/// dispatch cannot disagree.
pub fn known_service_names() -> Vec<&'static str> {
    macro_rules! collect {
        ($($proxy:ty),* $(,)?) => {
            vec![$(<$proxy>::SERVICE_NAME),*]
        };
    }
    let mut names = maintained_services!(collect);
    names.sort_unstable();
    names.dedup();
    names
}

/// Whether `name` is one of the services this gateway can advertise.
pub fn is_known_service(name: &str) -> bool {
    known_service_names().contains(&name)
}

/// Registers a Node.js provider service by its logical name.
///
/// Called from Node.js before `init`. The name must match exactly the parameter
/// of `#[service("Name")]`.
///
/// # Errors
/// `E_UNKNOWN_SERVICE` when the name is absent from the inventory,
/// `E_GATEWAY_STATE` when the gateway is already running.
pub fn register_service(service_name: &str) -> Result<(), GatewayError> {
    // The name is validated first: "unknown service" is more informative than
    // "wrong phase", and it keeps the answer independent of the current phase.
    if !is_known_service(service_name) {
        return Err(unknown_service_error(service_name));
    }
    if crate::state::phase() == Phase::Running {
        return Err(GatewayError::new(
            GatewayErrorCode::GatewayState,
            "registerService() must be called before init()",
        ));
    }

    maintained_services!(register_one_provider, service_name)?;

    crate::state::mark_configured()?;
    log::info!(
        "Service provider '{}' registered ({} total).",
        service_name,
        ice_rpc::locator().service_count()
    );
    Ok(())
}

/// Starts `initialize_all()` in the background.
///
/// Called by `init` once the bridge is live, so the caller is not blocked by
/// service announcement.
pub fn spawn_initialize_all() {
    let count = ice_rpc::locator().service_count();
    if count == 0 {
        log::warn!(
            "No service registered. Use gateway.registerService('Name') before gateway.init()."
        );
    }

    ice_rpc::rt::spawn(async move {
        log::info!("Initializing {} service(s)...", count);
        match ice_rpc::locator().initialize_all().await {
            Ok(()) => log::info!("All services are ready and announced on the IPC bus."),
            Err(e) => log::error!("Service initialization failed: {}", e),
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_maintained_list_is_the_advertised_surface() {
        let names = known_service_names();
        // The gateway maintains a subset of `common`'s services: it says which,
        // and adding one to `common` deliberately changes nothing here.
        assert_eq!(
            names,
            [
                "ConfigService",
                "ContextService",
                "DatabaseService",
                "HttpService",
                "NotificationService",
            ],
            "the advertised names are the maintained list"
        );
        // Sorted and deduplicated by construction.
        let mut sorted = names.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(names, sorted);

        for name in &names {
            assert!(is_known_service(name), "'{name}' must be known");
        }
        assert!(!is_known_service("NoSuchService"));
    }

    #[test]
    fn an_unknown_service_is_reported_with_the_known_ones() {
        let error = register_service("NoSuchService").expect_err("unknown name is refused");
        assert_eq!(error.code(), GatewayErrorCode::UnknownService);
        for name in known_service_names() {
            assert!(
                error.message().contains(name),
                "the message must list '{name}': {}",
                error.message()
            );
        }
    }
}
