//! Shared runtime state for the consumer-side clients generated by
//! `#[service]`.
//!
//! The reconnection callback, the reconnecting loop and the client bootstrap
//! (node creation, discovery, dispatch, publisher pre-creation) used to be
//! emitted into every generated client. They are factored here so the
//! generated code only holds a [`ClientCore`] and delegates to it.

use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex};

/// Runtime state shared by every generated client.
///
/// Owns the reconnection callback and the cached id of the provider node.
pub struct ClientCore {
    reconnect_cb: Arc<dyn Fn(u32) + Send + Sync>,
    cached_target_node: Arc<AtomicU64>,
    subscription: Mutex<Option<crate::node_supervisor::Subscription>>,
}

impl ClientCore {
    /// Builds the shared state and the reconnection callback for a service.
    pub fn new(service_name: &'static str) -> Self {
        let cached_target_node = Arc::new(AtomicU64::new(0));
        let reconnect_cb = build_reconnect_cb(service_name, cached_target_node.clone());

        Self {
            reconnect_cb,
            cached_target_node,
            subscription: Mutex::new(None),
        }
    }

    /// Subscribes to the node supervisor for a target node (idempotent).
    ///
    /// Replaces the previous subscription when the target node changes. The
    /// old subscription is removed via `Drop`.
    pub fn subscribe(&self, node_id: u32) {
        let mut subscription = self
            .subscription
            .lock()
            .expect("client core subscription lock poisoning");
        if let Some(existing) = subscription.as_ref() {
            if existing.node_id() == node_id {
                return;
            }
        }
        let cb = self.reconnect_cb.clone();
        *subscription =
            Some(crate::node_supervisor::NodeSupervisor::global().subscribe(node_id, cb));
    }

    /// Reads the cached target node id (`0` when unknown).
    pub fn cached_target_node(&self) -> u64 {
        self.cached_target_node.load(Ordering::Acquire)
    }

    /// Caches the target node id after a successful lookup or bootstrap.
    pub fn store_target_node(&self, node_id: u32) {
        self.cached_target_node
            .store(node_id as u64, Ordering::Release);
    }

    /// Bootstraps the client: creates the node, starts discovery, locates the
    /// provider, starts the dispatch loop and pre-creates the publishers.
    ///
    /// # Returns
    /// `true` when the target provider is ready; `false` otherwise.
    pub async fn init(&self, service_name: &'static str) -> bool {
        match crate::ServiceLocator::global().get_node_sync() {
            Ok(_) => {}
            Err(e) => {
                log::error!("[{}Client] get_node failed: {}", service_name, e);
                return false;
            }
        };

        {
            let locator = crate::ServiceLocator::global();
            let _ = crate::rt::spawn_blocking(move || {
                locator.start_discovery();
            })
            .await;
        }

        let discovery = crate::ServiceLocator::global().node_discovery();
        let target_node = match discovery.locate_service(service_name) {
            Some(n) => n,
            None => {
                log::warn!(
                    "[{}Client] Service '{}' not detected yet (empty cache+Blackboard).",
                    service_name,
                    service_name
                );
                return false;
            }
        };

        {
            let locator = crate::ServiceLocator::global();
            let _ = crate::rt::spawn_blocking(move || {
                locator.start_dispatch_if_needed();
            })
            .await;
        }

        let result = crate::rt::spawn_blocking_value(move || {
            crate::ServiceLocator::global()
                .hub()
                .ensure_publishers(target_node)
        })
        .await;

        match result {
            Ok(()) => {}
            Err(e) => {
                log::error!("[{}Client] ensure_publishers failed: {}", service_name, e);
                return false;
            }
        }

        self.store_target_node(target_node.0);
        self.subscribe(target_node.0);

        log::info!(
            "[{}Client] Ready (publishers pre-created, centralized hub).",
            service_name
        );
        true
    }
}

/// Builds the reconnection callback fired when the provider node dies.
fn build_reconnect_cb(
    service_name: &'static str,
    cached_target_node: Arc<AtomicU64>,
) -> Arc<dyn Fn(u32) + Send + Sync> {
    let reconnecting = Arc::new(AtomicBool::new(false));
    let server_ready = Arc::new(AtomicBool::new(false));

    Arc::new(move |dead_node_id: u32| {
        if reconnecting.swap(true, Ordering::SeqCst) {
            return;
        }
        log::warn!(
            "[{}Client] Node {} detected dead — reconnecting",
            service_name,
            dead_node_id
        );
        server_ready.store(false, Ordering::SeqCst);
        cached_target_node.store(0, Ordering::SeqCst);

        crate::ServiceLocator::global()
            .node_discovery()
            .invalidate_node_services(crate::NodeId(dead_node_id));
        crate::ServiceLocator::global()
            .hub()
            .invalidate_publishers(crate::NodeId(dead_node_id));

        let reconnecting_loop = reconnecting.clone();
        let ready_loop = server_ready.clone();
        let cached_node_loop = cached_target_node.clone();
        let cancel = crate::global_cancel_token().clone();
        std::thread::spawn(move || {
            let discovery = crate::ServiceLocator::global().node_discovery();
            let poll = std::time::Duration::from_millis(crate::INIT_RETRY_INTERVAL_MS);
            loop {
                if cancel.is_cancelled() {
                    break;
                }
                if let Some(nid) = discovery.locate_service(service_name) {
                    log::info!(
                        "[{}Client] Service found again — reconnection ok",
                        service_name
                    );
                    cached_node_loop.store(nid.0 as u64, Ordering::SeqCst);
                    ready_loop.store(true, Ordering::SeqCst);
                    reconnecting_loop.store(false, Ordering::SeqCst);
                    break;
                }
                std::thread::sleep(poll);
            }
        });
    })
}
