//! Internal facade consumed by the code generated by `ice-rpc-macros`.
//!
//! The `#[service]` procedural macro emits code that depends on a few
//! runtime internals. They are grouped here — instead of being re-exported
//! at the crate root — so that the stable public API of `ice-rpc` stays
//! small while the internals can evolve independently.
//!
//! This module is `#[doc(hidden)]` and is **not** part of the public API.

pub use crate::blackboard::{create_node_blackboard, list_services};
pub use crate::client_core::ClientCore;
pub use crate::hub::{NodeHub, RequestHandler, ResponseHandler};
pub use crate::node_discovery::{DiscoveryEvent, NodeDiscovery, NodeRecord};
pub use crate::node_lock::{
    acquire_global_node_lock, is_node_alive, register_node_lock_watcher, release_global_node_lock,
    unregister_node_lock_watcher, NodeLockWatcher, LOCK_WATCHER_POLL_MS,
};
pub use crate::node_supervisor::{
    fire as fire_reconnect_callbacks, NodeSupervisor, ReconnectCallback, Subscription, SubscriberId,
};
pub use crate::client_core::ConnectionState;
pub use crate::reconnect_manager::{PendingService, ReconnectManager};
pub use crate::registry_listener::spawn as spawn_node_registry_listener;
pub use crate::registry_notify::{announce_dead_node, announce_node_ready};
