#![allow(missing_docs)] // test target: documented by Readme.md, not part of a published API
#![allow(clippy::unwrap_used)] // tests may panic
                               // Integration tests for the `{Service}Decoder` generated by `#[service]` under the
                               // `monitoring` feature.
                               //
                               // A service type must never be forced to implement `Display` (the CI regression
                               // this file guards): the generated decoder renders each method argument and each
                               // response value with its own `Display` implementation when it has one, and falls
                               // back to its `Debug` implementation otherwise.

use ice_rpc::gen::WireEvent;
use ice_rpc::monitor::{Decoders, ServiceDecoder};
use ice_rpc::{service, Observable};
use rkyv::{Archive, Deserialize, Serialize};

/// No `Display`: only the `Debug` every generated request enum already requires.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Archive,
    Serialize,
    Deserialize,
    serde::Serialize,
    serde::Deserialize,
)]
pub enum Status {
    /// Nominal.
    Ok,
    /// Not operational.
    Nok,
}

/// Implements `Display`: its hand-written rendering must be preferred.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Archive,
    Serialize,
    Deserialize,
    serde::Serialize,
    serde::Deserialize,
)]
pub struct Label(pub u32);

impl std::fmt::Display for Label {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "label#{}", self.0)
    }
}

/// Service mixing an argument without `Display` and one with a hand-written one.
#[service("DecoderRendering")]
#[async_trait::async_trait]
pub trait DecoderRendering: Send + Sync + 'static {
    /// Would not compile if the generated decoder forced `Display` on `Status`.
    async fn set(&self, status: Status, label: Label) -> Observable<Status, String>;
}

/// Encodes a value exactly like the transport does.
fn encode<T>(value: &T) -> Vec<u8>
where
    T: for<'a> rkyv::Serialize<
        rkyv::rancor::Strategy<
            rkyv::ser::Serializer<
                rkyv::util::AlignedVec,
                rkyv::ser::allocator::ArenaHandle<'a>,
                rkyv::ser::sharing::Share,
            >,
            rkyv::rancor::Error,
        >,
    >,
{
    rkyv::to_bytes::<rkyv::rancor::Error>(value)
        .unwrap()
        .to_vec()
}

fn decoder() -> DecoderRenderingDecoder {
    DecoderRenderingDecoder
}

#[test]
fn generated_display_prefers_display_and_falls_back_to_debug() {
    let request = DecoderRenderingRequest::Set {
        status: Status::Nok,
        label: Label(7),
    };

    // `Status` has no `Display` (`Nok` is its `Debug` form), `Label` has one
    // (`label#7` rather than the derived `Label(7)`).
    assert_eq!(request.to_string(), "set(status=Nok, label=label#7)");
}

#[test]
fn generated_decoder_renders_requests() {
    let request = encode(&DecoderRenderingRequest::Set {
        status: Status::Ok,
        label: Label(1),
    });

    assert_eq!(
        decoder().request("set", &request).as_deref(),
        Some("set(status=Ok, label=label#1)")
    );
    assert_eq!(decoder().request("unknown", &request), None);
}

#[test]
fn generated_decoder_renders_responses() {
    let next = encode(&WireEvent::<Status, String>::Next(Status::Nok));
    assert_eq!(decoder().response("set", &next).as_deref(), Some("Nok"));

    // `String` implements `Display`: the error is not `Debug`-quoted.
    let error = encode(&WireEvent::<Status, String>::Error(String::from("boom")));
    assert_eq!(
        decoder().response("set", &error).as_deref(),
        Some("error: boom")
    );

    let complete = encode(&WireEvent::<Status, String>::Complete);
    assert_eq!(
        decoder().response("set", &complete).as_deref(),
        Some("complete")
    );

    // Undecodable bytes and unknown methods render nothing.
    assert_eq!(decoder().response("set", &[0xff, 0x00]), None);
    assert_eq!(decoder().response("unknown", &next), None);
}

#[test]
fn generated_decoder_registers_its_service() {
    let mut decoders = Decoders::new();
    DecoderRenderingDecoder::register(&mut decoders);

    assert_eq!(decoders.len(), 1);
    assert!(!decoders.is_empty());
}
