/**
 * Provider ContextService — example of an ice-rpc service in Node.js.
 *
 * This script starts the gateway in PROVIDER mode for the ContextService.
 * The business logic is in JavaScript; the Rust code generated by the
 * `#[service]` macro bridges the IPC bus (iceoryx2/rkyv) and Node.js (N-API).
 *
 * Architecture:
 *   Consumer (another process) → IPC (rkyv) → Rust Gateway → N-API → Node.js
 *   Node.js → N-API → Rust Gateway → IPC (rkyv) → Consumer
 *
 * ## Service registration
 *
 * Only the services that THIS process implements (Provider mode) are
 * registered via `gateway.registerService()`. The consumers towards other
 * IPC services are created automatically on demand by the ServiceLocator
 * — no declaration needed.
 *
 * Usage:
 *   node examples/provider-context.js
 */

const gateway = require('../index.js');

const store = new Map();

store.set('app.name', 'ice-rpc-gateway');
store.set('app.version', '1.0.0');
store.set('app.environment', 'development');
store.set('session.timeout', '3600');
store.set('feature.flags', '{"debug":true,"cache":true}');

(function preloadLargePayload() {
    const items = [];
    for (let i = 0; i < 50; i++) {
        items.push({
            id: i,
            name: `item-${String(i).padStart(3, '0')}`,
            description: `Large test item to validate the JSON serialization performance. Item number ${i}`,
            tags: ['tag-a', 'tag-b', 'tag-c'],
            metadata: {
                created: `2026-06-21T${String(i % 24).padStart(2, '0')}:00:00Z`,
                score: i * 1.5,
                active: i % 2 === 0
            }
        });
    }
    const largePayload = JSON.stringify(items);
    store.set('large.payload', largePayload);
    console.log(`[init] Entry 'large.payload' preloaded (${largePayload.length} bytes, ~${(largePayload.length / 1024).toFixed(1)} KB)`);
})();

function handleGet(key) {
    if (!key || key.length === 0) {
        return { type: 'error', data: 'InvalidKey' };
    }
    const value = store.get(key);
    if (value === undefined) {
        return { type: 'error', data: 'KeyNotFound' };
    }
    return { type: 'next', data: value };
}

function handleSet(key, value) {
    if (!key || key.length === 0) {
        return { type: 'error', data: 'InvalidKey' };
    }
    if (value === null || value === undefined) {
        return { type: 'error', data: 'InvalidValue' };
    }
    store.set(key, String(value));
    return { type: 'next', data: true };
}

function handleDelete(key) {
    if (!key || key.length === 0) {
        return { type: 'error', data: 'InvalidKey' };
    }
    const existed = store.delete(key);
    return { type: 'next', data: existed };
}

function handleList() {
    const entries = [];
    for (const [key, value] of store) {
        entries.push({ key, value });
    }
    if (entries.length > 0) {
        return { type: 'next', data: entries[0] };
    }
    return { type: 'complete' };
}

/**
 * Main dispatcher — called for ALL registered services.
 *
 * @param {Error|null} err - Potential N-API error.
 * @param {Object} call - Call object { correlationId, service, method, args }.
 */
function dispatch(err, call) {
    if (err) {
        console.error(`  ✕ NAPI error: ${err.message || err}`);
        return;
    }
    if (!call || typeof call !== 'object') {
        console.error('  ✕ Callback received null or invalid:', call);
        return;
    }
    const { correlationId, service, method, args } = call;

    const isDebug = process.env.DEBUG;
    if (isDebug) {
        const timestamp = new Date().toISOString().split('T')[1].slice(0, 12);
        const argsStr = typeof args === 'string' ? args : JSON.stringify(args);
        const argsPreview = argsStr.length > 120
            ? argsStr.substring(0, 120) + `... [${argsStr.length} bytes total]`
            : argsStr;
        console.log(`\n[${timestamp}] IPC → ${service}::${method}`);
        console.log(`  args: ${argsPreview}`);
        console.log(`  cid:  ${correlationId}`);
    }

    let result;
    switch (service) {
        case 'ContextService':
            switch (method) {
                case 'get':
                    result = handleGet(args);
                    break;
                case 'set':
                    result = handleSet(args.key, args.value);
                    break;
                case 'delete':
                    result = handleDelete(args);
                    break;
                case 'list':
                    result = handleList();
                    break;
                default:
                    result = { type: 'error', data: `Unknown method: ${method}` };
            }
            break;
        default: {
            if (isDebug) {
                console.warn(`  ⚠ Service '${service}' not implemented in this process!`);
                console.warn(`    → Add a case for '${service}' in the dispatcher.`);
            }
            result = {
                type: 'error',
                data: `Service '${service}' not implemented in this NodeJS process`
            };
        }
    }

    if (isDebug) {
        const resultStr = JSON.stringify(result);
        const resultPreview = resultStr.length > 120
            ? resultStr.substring(0, 120) + `... [${resultStr.length} bytes total]`
            : resultStr;
        console.log(`  ← result: ${resultPreview}`);
    }

    gateway.resolveNodejsCall(correlationId, result);
}

async function main() {
    console.log('=== PROVIDER CONTEXTSERVICE (NodeJS) ===');
    console.log('ProviderNodeJs mode — the business logic is in JavaScript.\n');

    // Register only the services that THIS process implements.
    // The consumers towards other IPC services are created automatically
    // by the ServiceLocator after gateway.init() — no need to declare them.
    console.log('Registering the Provider service...');
    if (!gateway.registerService('ContextService')) {
        console.error('ERROR: failed to register the service.');
        process.exit(1);
    }

    // init() automatically injects the consumer factory (generated by
    // common/build.rs). After this call, any known IPC service is accessible
    // via ServiceLocator::get() without extra registration.
    console.log('Initializing the gateway...');
    if (!gateway.init(dispatch)) {
        console.error('ERROR: failed to initialize the gateway.');
        process.exit(1);
    }

    console.log('Gateway initialized.');
    console.log('Services announced on the IPC bus:');
    console.log('  - ContextService   (ProviderNodeJs — implemented in this process)');
    console.log('\n');

    // ── Consumer: calls to the Rust provider (provider-app) ─────
    // After init, the ServiceLocator can instantiate any known proxy
    // (DatabaseServiceProxy, ConfigServiceProxy, etc.) on demand.
    // We wait a short delay so that the IPC discovery finds the provider.
    console.log('=== CONSUMER: requests to the Rust provider ===');

    const namesToTest = ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Max'];
    let totalMs = 0;
    let successCount = 0;

    for (const name of namesToTest) {
        const t0 = performance.now();
        try {
            const age = await gateway.callService('DatabaseService', 'get_user_age', name);
            const ms = (performance.now() - t0).toFixed(3);
            totalMs += parseFloat(ms);
            successCount++;
            console.log(`  ✓ get_user_age("${name}") → ${age} years  [${ms}ms]`);
        } catch (err) {
            const ms = (performance.now() - t0).toFixed(3);
            console.log(`  ✗ get_user_age("${name}") → ${err.message || err}  [${ms}ms]`);
        }
    }

    if (successCount > 0) {
        const avgMs = (totalMs / successCount).toFixed(3);
        console.log(`\n  ── Average: ${avgMs}ms (${successCount} successful request(s))`);
    }

    console.log('\nWaiting for IPC requests... (Ctrl+C to quit)\n');

    let shuttingDown = false;

    const cleanup = async () => {
        if (shuttingDown) return;
        shuttingDown = true;
        console.log('\n\nShutting down...');
        if (process.stdin.isTTY) {
            try { process.stdin.setRawMode(false); } catch (_) {}
            process.stdin.pause();
        }
        try {
            gateway.shutdown();
            await new Promise(resolve => setTimeout(resolve, 500));
        } catch (e) {
            console.error('Error during shutdown:', e);
        }
        console.log('Gateway stopped.');
        process.exit(0);
    };

    const readline = require('readline');
    readline.emitKeypressEvents(process.stdin);
    if (process.stdin.isTTY) {
        process.stdin.setRawMode(true);
    }
    process.stdin.on('keypress', (str, key) => {
        if (key && key.ctrl && key.name === 'c') {
            cleanup();
        } else if (key && key.name === 'q') {
            console.log('\nQ key pressed — stopping.');
            cleanup();
        }
    });
    process.stdin.resume();

    process.on('SIGINT', cleanup);
    process.on('SIGTERM', cleanup);
    process.on('uncaughtException', (err) => {
        console.error('Uncaught exception:', err);
        cleanup();
    });
}

main().catch(err => {
    console.error('Fatal error:', err);
    process.exit(1);
});
