//! The pull-based [`Observable`] — the concrete stream type returned by services.
//!
//! `Observable` is the push→pull boundary: it wraps either a transport channel,
//! an inline buffer (`of`/`from`) or a boxed operator pipeline, and always
//! presents the same normalized sequence of [`Event`]s.
//!
//! Internally the storage enum is still called `StreamInner` (the transport is a
//! byte stream); `Observable` is the public Rx vocabulary exposed by `ice-rpc`.

use std::pin::Pin;
use std::task::{Context, Poll};

use super::error::RpcError;
use super::wire::{normalize_wire_event, Event, ObservableError, Sender, WireEvent};

pin_project_lite::pin_project! {
    /// Internal storage backing an [`Observable`].
    ///
    /// Three sources, each with its own cost contract:
    /// - `Transport` is the transport-backed variant used by RPC calls: the
    ///   iceoryx2 side pushes [`WireEvent`]s while the consumer pulls.
    /// - `Inline` is a pure, already-computed source used by
    ///   `of`/`from`/`throw_error` — no channel, no task, and an inline
    ///   queue: no `Arc`, no lock.
    /// - `Pipeline` wraps any `futures_lite::Stream` of [`Event`], which is
    ///   what makes an **operator pipeline** returnable by a service method
    ///   (see [`Observable::from_stream`]).
    #[project = StreamInnerProj]
    enum StreamInner<T, E> {
        Transport {
            #[pin]
            rx: async_channel::Receiver<WireEvent<T, E>>,
            // Buffered `Complete` left over after expanding a `CompleteWith`.
            pending: Option<Event<T, E>>,
        },
        Inline {
            // Single-consumer queue: read through `&mut self` (see `recv`).
            queue: std::collections::VecDeque<Event<T, E>>,
        },
        Pipeline {
            // `Pin<Box<…>>` so the wrapped stream need not be `Unpin` (our own
            // `Observable` is not, since its `Transport` variant holds a `Receiver`).
            stream: Pin<Box<dyn futures_lite::Stream<Item = Event<T, E>> + Send>>,
            // One-event look-ahead, used to fold `Next(v) + Complete` into the
            // single-sample `CompleteWith` optimization.
            pending: Option<Event<T, E>>,
        },
    }
}

/// Owner token whose `Drop` fires the cleanup exactly once, when the
/// [`Observable`] holding it is dropped.
struct OnDropToken(Box<dyn Fn() + Send + Sync + 'static>);

impl Drop for OnDropToken {
    fn drop(&mut self) {
        (self.0)();
    }
}

/// Fires a cleanup callback exactly once, when the [`Observable`] is dropped.
///
/// This is what turns "the consumer abandoned the stream" into an O(1) hub
/// cleanup — no scan, no lock on the dispatch path (audit C14).
// The field is never read: its purpose is to *own* the token so that its `Drop`
// runs. `allow(dead_code)` is therefore intentional.
#[allow(dead_code)]
struct OnDropCleanup(Option<OnDropToken>);

pin_project_lite::pin_project! {
    /// Consumer-side receiver of RPC events.
    ///
    /// This is the concrete type behind the public [`Observable`] name, and the
    /// return type of every method generated by `#[service]`.
    ///
    /// [`Observable::recv`] yields user-facing [`Event`] values only — the
    /// transport `CompleteWith` optimization is normalized away. Raw transport
    /// events are available through [`Observable::recv_wire`] (used by the
    /// server relay).
    ///
    /// An `Observable` is **single-subscription**: it deliberately does not
    /// implement `Clone`. To fan a stream out to several consumers, use
    /// `Subject` / `ShareReplay` (each subscriber gets its own channel and
    /// receives every event) instead of duplicating a handle.
    pub struct Observable<T, E> {
        #[pin]
        inner: StreamInner<T, E>,
        // Not pinned: dropping it fires the abandoned-call cleanup (C14).
        on_drop: OnDropCleanup,
    }
}

impl<T, E> Observable<T, E> {
    /// Attaches a cleanup callback fired when the observable is dropped.
    ///
    /// Used by the generated client to release the hub entry of a call the
    /// consumer abandoned (`timeout`, `first_value()`, `take(1)`, early return,
    /// `switch_map`, …) without scanning the hub tables (audit C14).
    #[doc(hidden)]
    pub fn with_on_drop(mut self, cleanup: impl Fn() + Send + Sync + 'static) -> Self {
        self.on_drop = OnDropCleanup(Some(OnDropToken(Box::new(cleanup))));
        self
    }

    /// Builds a pure, channel-free observable from an already-computed event
    /// list.
    ///
    /// Used by the `of`/`from` constructors and by
    /// [`Observable::from_technical_error`]. The events are stored in an inline
    /// `VecDeque`: a single allocation, no `Arc`, no mutex.
    #[doc(hidden)]
    pub fn from_events(events: impl IntoIterator<Item = Event<T, E>>) -> Self {
        Self {
            inner: StreamInner::Inline {
                queue: events.into_iter().collect(),
            },
            on_drop: OnDropCleanup(None),
        }
    }

    /// Builds an observable that only emits a terminal technical error.
    ///
    /// Used when an RPC call fails before the transport stream exists (service
    /// not found, provider unreachable, discovery timeout, ...).
    #[doc(hidden)]
    pub fn from_technical_error(err: RpcError) -> Self {
        Self::from_events([Event::Error(ObservableError::Technical(err))])
    }

    /// Builds an [`Observable`] from any stream of [`Event`].
    ///
    /// This is what makes an **operator pipeline** usable as the return value of
    /// a service method: the generated proxy has a single return type for both
    /// its `Provider` (in-process implementation) and `Consumer` (IPC client)
    /// modes, so an operator type (`Map<…>`, `Delay<…>`, …) cannot be returned
    /// directly.
    ///
    /// The `CompleteWith` single-sample optimization is preserved: a `Next(v)`
    /// immediately followed by a `Complete` is folded into one wire sample.
    ///
    /// # Example
    /// ```rust,ignore
    /// async fn watch(&self, count: u32) -> Observable<u32, String> {
    ///     ice_rpc::Observable::from_stream(
    ///         ice_rpc_rx::from(1..=count).delay(Duration::from_millis(100)),
    ///     )
    /// }
    /// ```
    ///
    /// In practice `ice-rpc-rx` exposes the shorter
    /// `RxStreamExt::into_observable()`.
    #[doc(hidden)]
    pub fn from_stream<S>(stream: S) -> Self
    where
        S: futures_lite::Stream<Item = Event<T, E>> + Send + 'static,
        T: 'static,
        E: 'static,
    {
        Self {
            inner: StreamInner::Pipeline {
                stream: Box::pin(stream),
                pending: None,
            },
            on_drop: OnDropCleanup(None),
        }
    }

    /// Receives the next user-facing event.
    ///
    /// A transport `CompleteWith(v)` is replayed as `Next(v)` followed by
    /// `Complete`, so consumers never observe the optimization.
    ///
    /// Takes `&mut self` because an inline observable drains its queue without
    /// any interior mutability (no lock on the read path).
    pub async fn recv(&mut self) -> Result<Event<T, E>, async_channel::RecvError> {
        match &mut self.inner {
            StreamInner::Transport { rx, pending } => {
                if let Some(event) = pending.take() {
                    return Ok(event);
                }
                match rx.recv().await {
                    Ok(event) => {
                        let (current, follow_up) = normalize_wire_event(event);
                        if let Some(next) = follow_up {
                            *pending = Some(next);
                        }
                        Ok(current)
                    }
                    Err(e) => Err(e),
                }
            }
            StreamInner::Inline { queue } => match queue.pop_front() {
                Some(event) => Ok(event),
                None => Err(async_channel::RecvError),
            },
            StreamInner::Pipeline { stream, pending } => {
                if let Some(event) = pending.take() {
                    return Ok(event);
                }
                match futures_lite::future::poll_fn(|cx| {
                    futures_lite::Stream::poll_next(stream.as_mut(), cx)
                })
                .await
                {
                    Some(event) => Ok(event),
                    None => Err(async_channel::RecvError),
                }
            }
        }
    }

    /// Receives the next raw transport event (server relay only).
    ///
    /// For a transport-backed observable this is a plain passthrough of the
    /// producer [`WireEvent`]. For an inline observable (built by
    /// [`Observable::from_events`], i.e. `of` / `from` / `throw_error`) the last
    /// `Next(v)` followed by a `Complete` is folded back into the single-sample
    /// [`WireEvent::CompleteWith`] optimization, so a single-response service
    /// still travels as **one** iceoryx2 sample. Consumers never observe the
    /// difference: the client expands `CompleteWith` back into `Next` +
    /// `Complete`.
    #[doc(hidden)]
    pub async fn recv_wire(&mut self) -> Result<WireEvent<T, E>, async_channel::RecvError> {
        match &mut self.inner {
            StreamInner::Transport { rx, .. } => rx.recv().await,
            StreamInner::Pipeline { stream, pending } => {
                if let Some(event) = pending.take() {
                    return Ok(event.into());
                }
                futures_lite::future::poll_fn(|cx| {
                    match futures_lite::Stream::poll_next(Pin::new(&mut *stream), cx) {
                        Poll::Ready(None) => Poll::Ready(Err(async_channel::RecvError)),
                        Poll::Ready(Some(Event::Next(v))) => {
                            // Best-effort peek with the *same* context: if the
                            // `Complete` is already available it is folded into a
                            // single sample; otherwise the value is emitted now so
                            // a long-lived stream is never blocked.
                            match futures_lite::Stream::poll_next(Pin::new(&mut *stream), cx) {
                                Poll::Ready(Some(Event::Complete)) => {
                                    Poll::Ready(Ok(WireEvent::CompleteWith(v)))
                                }
                                Poll::Ready(other) => {
                                    *pending = other;
                                    Poll::Ready(Ok(WireEvent::Next(v)))
                                }
                                Poll::Pending => Poll::Ready(Ok(WireEvent::Next(v))),
                            }
                        }
                        Poll::Ready(Some(other)) => Poll::Ready(Ok(other.into())),
                        Poll::Pending => Poll::Pending,
                    }
                })
                .await
            }
            StreamInner::Inline { queue } => match queue.pop_front() {
                None => Err(async_channel::RecvError),
                Some(Event::Next(v)) => {
                    // A value immediately followed by `Complete` is exactly
                    // the `CompleteWith` single-sample case.
                    if matches!(queue.front(), Some(Event::Complete)) {
                        queue.pop_front();
                        Ok(WireEvent::CompleteWith(v))
                    } else {
                        Ok(WireEvent::Next(v))
                    }
                }
                Some(event) => Ok(event.into()),
            },
        }
    }

    /// Awaits the first emitted value of the observable.
    ///
    /// `Next(v)` → `Ok(v)`, `Error(e)` → `Err(e.into())`,
    /// `Complete`/closed → `Err(StreamError::Empty)`.
    ///
    /// Delegates to [`first_event`]: the single implementation shared with the
    /// `RxStreamExt::first_value` default method of `ice-rpc-rx`.
    pub async fn first_value(self) -> Result<T, StreamError<E>> {
        first_event(self).await
    }

    /// Collects every emitted value into a `Vec`.
    ///
    /// The observable is consumed until `Complete` (or until it is closed). On a
    /// terminal `Error` the collected values are discarded and the error is
    /// returned.
    ///
    /// Delegates to [`collect_values`]: the single implementation shared with the
    /// `RxStreamExt::collect` default method of `ice-rpc-rx`.
    pub async fn collect(self) -> Result<Vec<T>, ObservableError<E>> {
        collect_values(self).await
    }
}

/// Awaits the first event of any stream of [`Event`].
///
/// This is the **single** implementation behind [`Observable::first_value`] and
/// the `RxStreamExt::first_value` default method of `ice-rpc-rx`. The two
/// surfaces cannot share a method body directly (one is inherent, the other is a
/// trait default over a generic `Self`), so the logic lives here.
///
/// Reachable as `ice_rpc::gen::first_event`.
#[doc(hidden)]
pub async fn first_event<S, T, E>(stream: S) -> Result<T, StreamError<E>>
where
    S: futures_lite::Stream<Item = Event<T, E>>,
{
    let mut stream = std::pin::pin!(stream);
    match futures_lite::future::poll_fn(|cx| futures_lite::Stream::poll_next(stream.as_mut(), cx))
        .await
    {
        Some(Event::Next(v)) => Ok(v),
        Some(Event::Error(e)) => Err(e.into()),
        Some(Event::Complete) | None => Err(StreamError::Empty),
    }
}

/// Collects every value of any stream of [`Event`].
///
/// The stream is drained until `Complete` (or until it is closed). On a terminal
/// `Error` the collected values are discarded and the error is returned.
///
/// This is the **single** implementation behind [`Observable::collect`] and the
/// `RxStreamExt::collect` default method of `ice-rpc-rx`.
///
/// Reachable as `ice_rpc::gen::collect_values`.
#[doc(hidden)]
pub async fn collect_values<S, T, E>(stream: S) -> Result<Vec<T>, ObservableError<E>>
where
    S: futures_lite::Stream<Item = Event<T, E>>,
{
    let mut stream = std::pin::pin!(stream);
    let mut values = Vec::new();
    while let Some(event) =
        futures_lite::future::poll_fn(|cx| futures_lite::Stream::poll_next(stream.as_mut(), cx))
            .await
    {
        match event {
            Event::Next(v) => values.push(v),
            Event::Complete => return Ok(values),
            Event::Error(e) => return Err(e),
        }
    }
    // Source closed without a terminal event: return what was collected.
    Ok(values)
}

impl<T, E> futures_lite::Stream for Observable<T, E> {
    type Item = Event<T, E>;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        match self.project().inner.project() {
            StreamInnerProj::Transport { rx, pending } => {
                // A previous `CompleteWith` left a trailing `Complete` behind.
                if let Some(event) = pending.take() {
                    return Poll::Ready(Some(event));
                }

                match futures_lite::Stream::poll_next(rx, cx) {
                    Poll::Ready(Some(event)) => {
                        let (current, follow_up) = normalize_wire_event(event);
                        if let Some(next) = follow_up {
                            *pending = Some(next);
                        }
                        Poll::Ready(Some(current))
                    }
                    Poll::Ready(None) => Poll::Ready(None),
                    Poll::Pending => Poll::Pending,
                }
            }
            StreamInnerProj::Inline { queue } => match queue.pop_front() {
                Some(event) => Poll::Ready(Some(event)),
                None => Poll::Ready(None),
            },
            StreamInnerProj::Pipeline { stream, pending } => {
                if let Some(event) = pending.take() {
                    return Poll::Ready(Some(event));
                }
                futures_lite::Stream::poll_next(stream.as_mut(), cx)
            }
        }
    }
}

/// Error returned by [`Observable::first_value`].
///
/// `collect` returns [`ObservableError`] directly, since it cannot be empty.
#[derive(Debug, Clone)]
pub enum StreamError<E> {
    /// Business error emitted by the service.
    Business(E),
    /// Technical RPC error (call-level or in-stream).
    Technical(RpcError),
    /// The stream ended without emitting a value.
    Empty,
}

impl<E> From<ObservableError<E>> for StreamError<E> {
    #[inline]
    fn from(err: ObservableError<E>) -> Self {
        match err {
            ObservableError::Business(e) => StreamError::Business(e),
            ObservableError::Technical(e) => StreamError::Technical(e),
        }
    }
}

impl<E: std::fmt::Display> std::fmt::Display for StreamError<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            StreamError::Business(e) => write!(f, "{e}"),
            StreamError::Technical(e) => write!(f, "{e}"),
            StreamError::Empty => write!(f, "stream ended without a value"),
        }
    }
}

impl<E: std::fmt::Debug + std::fmt::Display> std::error::Error for StreamError<E> {}

/// Creates a bounded channel of RPC events.
///
/// Runtime-agnostic replacement for `tokio::sync::mpsc::channel`. This is the
/// transport boundary: producers push, the returned [`Observable`] pulls.
pub fn channel<T, E>(capacity: usize) -> (Sender<T, E>, Observable<T, E>) {
    let (tx, rx) = async_channel::bounded::<WireEvent<T, E>>(capacity);
    (
        Sender { inner: tx },
        Observable {
            inner: StreamInner::Transport { rx, pending: None },
            on_drop: OnDropCleanup(None),
        },
    )
}

/// Creates an **unbounded** channel of RPC events.
///
/// Used for the per-call response path. The dispatch loop delivers responses
/// from a synchronous callback and therefore cannot apply backpressure
/// (`send().await`); a bounded channel would turn a slow consumer into a
/// **silent** loss (audit C3a/C3b). An unbounded channel removes the loss
/// point entirely, and the `Drop` cleanup attached by the generated client
/// (audit C14) frees the queue and the hub entry as soon as the last handle of
/// the stream is dropped.
pub fn unbounded_channel<T, E>() -> (Sender<T, E>, Observable<T, E>) {
    let (tx, rx) = async_channel::unbounded::<WireEvent<T, E>>();
    (
        Sender { inner: tx },
        Observable {
            inner: StreamInner::Transport { rx, pending: None },
            on_drop: OnDropCleanup(None),
        },
    )
}
