//! The pull-based [`Observable`] — the concrete stream type returned by services.
//!
//! `Observable` is the push→pull boundary: it wraps either a transport channel,
//! an inline buffer (`of`/`from`) or a boxed operator pipeline, and always
//! presents the same normalized sequence of [`Event`]s.

use std::pin::Pin;
use std::task::{Context, Poll};

use super::error::RpcError;
use super::wire::{normalize_wire_event, Event, ObservableError, Sender, WireEvent};

pin_project_lite::pin_project! {
    /// Internal storage backing an [`Observable`].
    ///
    /// Three sources: `Transport` (transport-backed RPC call), `Inline`
    /// (already-computed `of`/`from` events) and `Pipeline` (a boxed operator
    /// stream).
    #[project = StreamInnerProj]
    enum StreamInner<T, E> {
        Transport {
            #[pin]
            rx: async_channel::Receiver<WireEvent<T, E>>,
            // Buffered `Complete` left over after expanding a `CompleteWith`.
            pending: Option<Event<T, E>>,
        },
        Inline {
            // Single-consumer queue: read through `&mut self` (see `recv`).
            queue: std::collections::VecDeque<Event<T, E>>,
        },
        Pipeline {
            // Boxed so the wrapped stream need not be `Unpin`.
            stream: Pin<Box<dyn futures_lite::Stream<Item = Event<T, E>> + Send>>,
            // One-event look-ahead, used to fold `Next(v) + Complete` into the
            // single-sample `CompleteWith` optimization.
            pending: Option<Event<T, E>>,
        },
    }
}

pin_project_lite::pin_project! {
    /// Consumer-side receiver of RPC events.
    ///
    /// The concrete type behind the public [`Observable`] name and the return
    /// type of every method generated by `#[service]`. Two pull-based styles:
    /// [`Observable::recv`] yields the full [`Event`] vocabulary, while
    /// [`Observable::next`] yields `Option<Result<T, ObservableError<E>>>`.
    ///
    /// Both normalize the transport `CompleteWith` optimization away; raw
    /// transport events stay internal (`recv_wire`).
    ///
    /// An `Observable` is **single-subscription** (it does not implement
    /// `Clone`): use `Subject` to fan a stream out to several consumers.
    pub struct Observable<T, E> {
        #[pin]
        inner: StreamInner<T, E>,
        // Set as soon as a terminal event (`Complete` / `Error`) has been
        // delivered, so that a later channel close is reported as a normal end
        // (`None` from `next`) instead of an abrupt one.
        terminated: bool,
    }
}

impl<T, E> Observable<T, E> {
    /// Builds a pure, channel-free observable from an already-computed event
    /// list.
    ///
    /// Used by the `of`/`from` constructors and by
    /// [`Observable::from_technical_error`]. The events are stored in an inline
    /// `VecDeque`: a single allocation, no `Arc`, no mutex.
    #[doc(hidden)]
    pub fn from_events(events: impl IntoIterator<Item = Event<T, E>>) -> Self {
        Self {
            inner: StreamInner::Inline {
                queue: events.into_iter().collect(),
            },
            terminated: false,
        }
    }

    /// Builds an observable that only emits a terminal technical error.
    ///
    /// Used when an RPC call fails before the transport stream exists (service
    /// not found, provider unreachable, discovery timeout, ...).
    #[doc(hidden)]
    pub fn from_technical_error(err: RpcError) -> Self {
        Self::from_events([Event::Error(ObservableError::Technical(err))])
    }

    /// Builds an [`Observable`] from any stream of [`Event`].
    ///
    /// Makes **any** poll-based stream usable as the return value of a service
    /// method. The `CompleteWith` single-sample optimization is preserved: a
    /// `Next(v)` immediately followed by a `Complete` is folded into one sample.
    ///
    /// # Example
    /// ```rust,ignore
    /// async fn watch(&self, count: u32) -> Observable<u32, String> {
    ///     ice_rpc::from(1..=count).delay(Duration::from_millis(100))
    /// }
    /// ```
    #[doc(hidden)]
    pub fn from_stream<S>(stream: S) -> Self
    where
        S: futures_lite::Stream<Item = Event<T, E>> + Send + 'static,
        T: 'static,
        E: 'static,
    {
        Self {
            inner: StreamInner::Pipeline {
                stream: Box::pin(stream),
                pending: None,
            },
            terminated: false,
        }
    }

    /// Receives the next user-facing event — the full [`Event`] vocabulary.
    ///
    /// A transport `CompleteWith(v)` is replayed as `Next(v)` then `Complete`.
    /// `Err(RecvError)` means the source closed: a normal end if a terminal event
    /// was already delivered, an abrupt close otherwise.
    ///
    /// Takes `&mut self` because an inline observable drains its queue without
    /// interior mutability.
    pub async fn recv(&mut self) -> Result<Event<T, E>, async_channel::RecvError> {
        let event = match &mut self.inner {
            StreamInner::Transport { rx, pending } => {
                if let Some(event) = pending.take() {
                    Ok(event)
                } else {
                    match rx.recv().await {
                        Ok(event) => {
                            let (current, follow_up) = normalize_wire_event(event);
                            if let Some(next) = follow_up {
                                *pending = Some(next);
                            }
                            Ok(current)
                        }
                        Err(e) => Err(e),
                    }
                }
            }
            StreamInner::Inline { queue } => match queue.pop_front() {
                Some(event) => Ok(event),
                None => Err(async_channel::RecvError),
            },
            StreamInner::Pipeline { stream, pending } => {
                if let Some(event) = pending.take() {
                    Ok(event)
                } else {
                    match futures_lite::future::poll_fn(|cx| {
                        futures_lite::Stream::poll_next(stream.as_mut(), cx)
                    })
                    .await
                    {
                        Some(event) => Ok(event),
                        None => Err(async_channel::RecvError),
                    }
                }
            }
        };

        if let Ok(delivered) = &event {
            if delivered.is_terminal() {
                self.terminated = true;
            }
        }
        event
    }

    /// Awaits the next emitted value: the concise view over
    /// [`Observable::recv`].
    ///
    /// - `Next(v)`  → `Some(Ok(v))`
    /// - `Error(e)` → `Some(Err(e))`
    /// - `Complete` → `None`
    ///
    /// `None` always means *the producer completed cleanly*: a source that
    /// closes without a terminal event is reported as a technical error first.
    pub async fn next(&mut self) -> Option<Result<T, ObservableError<E>>> {
        match self.recv().await {
            Ok(Event::Next(v)) => Some(Ok(v)),
            Ok(Event::Error(e)) => Some(Err(e)),
            Ok(Event::Complete) => None,
            Err(_) if self.terminated => None,
            Err(_) => {
                // Abrupt end: report it once, then treat the stream as over.
                self.terminated = true;
                Some(Err(ObservableError::Technical(RpcError::TransportError(
                    "stream closed before completion".to_string(),
                ))))
            }
        }
    }

    /// Receives the next raw transport event (server relay only).
    ///
    /// For an inline observable the last `Next(v)` followed by a `Complete` is
    /// folded back into the single-sample [`WireEvent::CompleteWith`]
    /// optimization, so a single-response service travels as one iceoryx2
    /// sample.
    pub(crate) async fn recv_wire(&mut self) -> Result<WireEvent<T, E>, async_channel::RecvError> {
        match &mut self.inner {
            StreamInner::Transport { rx, .. } => rx.recv().await,
            StreamInner::Pipeline { stream, pending } => {
                if let Some(event) = pending.take() {
                    return Ok(event.into());
                }
                futures_lite::future::poll_fn(|cx| {
                    match futures_lite::Stream::poll_next(Pin::new(&mut *stream), cx) {
                        Poll::Ready(None) => Poll::Ready(Err(async_channel::RecvError)),
                        Poll::Ready(Some(Event::Next(v))) => {
                            // Best-effort peek with the same context: fold the
                            // `Complete` into one sample when it is available.
                            match futures_lite::Stream::poll_next(Pin::new(&mut *stream), cx) {
                                Poll::Ready(Some(Event::Complete)) => {
                                    Poll::Ready(Ok(WireEvent::CompleteWith(v)))
                                }
                                Poll::Ready(other) => {
                                    *pending = other;
                                    Poll::Ready(Ok(WireEvent::Next(v)))
                                }
                                Poll::Pending => Poll::Ready(Ok(WireEvent::Next(v))),
                            }
                        }
                        Poll::Ready(Some(other)) => Poll::Ready(Ok(other.into())),
                        Poll::Pending => Poll::Pending,
                    }
                })
                .await
            }
            StreamInner::Inline { queue } => match queue.pop_front() {
                None => Err(async_channel::RecvError),
                Some(Event::Next(v)) => {
                    // A value immediately followed by `Complete` is exactly
                    // the `CompleteWith` single-sample case.
                    if matches!(queue.front(), Some(Event::Complete)) {
                        queue.pop_front();
                        Ok(WireEvent::CompleteWith(v))
                    } else {
                        Ok(WireEvent::Next(v))
                    }
                }
                Some(event) => Ok(event.into()),
            },
        }
    }

    /// Awaits the first emitted value of the observable.
    ///
    /// `Next(v)` → `Ok(v)`, `Error(e)` → `Err(e)`,
    /// `Complete`/closed → `Err(ObservableError::Empty)`.
    ///
    /// Delegates to [`first_event`], the canonical terminal implementation.
    pub async fn first_value(self) -> Result<T, ObservableError<E>> {
        first_event(self).await
    }

    /// Collects every emitted value into a `Vec`.
    ///
    /// The observable is consumed until `Complete` (or until it is closed). On a
    /// terminal `Error` the collected values are discarded and the error is
    /// returned.
    ///
    /// Delegates to [`collect_values`], the canonical terminal implementation.
    pub async fn collect(self) -> Result<Vec<T>, ObservableError<E>> {
        collect_values(self).await
    }
}

/// Awaits the first event of any stream of [`Event`].
///
/// This is the **single** implementation behind [`Observable::first_value`];
/// living in a free function lets the generated code and the operators reuse it
/// on a raw `futures_lite::Stream`.
///
/// Reachable as `ice_rpc::gen::first_event`.
#[doc(hidden)]
pub async fn first_event<S, T, E>(stream: S) -> Result<T, ObservableError<E>>
where
    S: futures_lite::Stream<Item = Event<T, E>>,
{
    let mut stream = std::pin::pin!(stream);
    match futures_lite::future::poll_fn(|cx| futures_lite::Stream::poll_next(stream.as_mut(), cx))
        .await
    {
        Some(Event::Next(v)) => Ok(v),
        Some(Event::Error(e)) => Err(e),
        Some(Event::Complete) | None => Err(ObservableError::Empty),
    }
}

/// Collects every value of any stream of [`Event`].
///
/// The stream is drained until `Complete` (or until it is closed). On a terminal
/// `Error` the collected values are discarded and the error is returned.
///
/// This is the **single** implementation behind [`Observable::collect`].
///
/// Reachable as `ice_rpc::gen::collect_values`.
#[doc(hidden)]
pub async fn collect_values<S, T, E>(stream: S) -> Result<Vec<T>, ObservableError<E>>
where
    S: futures_lite::Stream<Item = Event<T, E>>,
{
    let mut stream = std::pin::pin!(stream);
    let mut values = Vec::new();
    while let Some(event) =
        futures_lite::future::poll_fn(|cx| futures_lite::Stream::poll_next(stream.as_mut(), cx))
            .await
    {
        match event {
            Event::Next(v) => values.push(v),
            Event::Complete => return Ok(values),
            Event::Error(e) => return Err(e),
        }
    }
    // Source closed without a terminal event: return what was collected.
    Ok(values)
}

impl<T, E> futures_lite::Stream for Observable<T, E> {
    type Item = Event<T, E>;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let this = self.project();
        let polled = match this.inner.project() {
            StreamInnerProj::Transport { rx, pending } => {
                // A previous `CompleteWith` left a trailing `Complete` behind.
                if let Some(event) = pending.take() {
                    Poll::Ready(Some(event))
                } else {
                    match futures_lite::Stream::poll_next(rx, cx) {
                        Poll::Ready(Some(event)) => {
                            let (current, follow_up) = normalize_wire_event(event);
                            if let Some(next) = follow_up {
                                *pending = Some(next);
                            }
                            Poll::Ready(Some(current))
                        }
                        Poll::Ready(None) => Poll::Ready(None),
                        Poll::Pending => Poll::Pending,
                    }
                }
            }
            StreamInnerProj::Inline { queue } => match queue.pop_front() {
                Some(event) => Poll::Ready(Some(event)),
                None => Poll::Ready(None),
            },
            StreamInnerProj::Pipeline { stream, pending } => {
                if let Some(event) = pending.take() {
                    Poll::Ready(Some(event))
                } else {
                    futures_lite::Stream::poll_next(stream.as_mut(), cx)
                }
            }
        };

        // Keep `terminated` in sync for callers that poll the stream directly
        // (`as_stream` pipelines, `Subject` relays) before falling back to
        // `recv` / `next`.
        if let Poll::Ready(Some(event)) = &polled {
            if event.is_terminal() {
                *this.terminated = true;
            }
        }
        polled
    }
}

/// Creates a bounded channel of RPC events.
///
/// Runtime-agnostic replacement for `tokio::sync::mpsc::channel`. This is the
/// transport boundary: producers push, the returned [`Observable`] pulls.
pub fn channel<T, E>(capacity: usize) -> (Sender<T, E>, Observable<T, E>) {
    let (tx, rx) = async_channel::bounded::<WireEvent<T, E>>(capacity);
    (
        Sender { inner: tx },
        Observable {
            inner: StreamInner::Transport { rx, pending: None },
            terminated: false,
        },
    )
}

/// Creates an **unbounded** channel of RPC events.
///
/// Used for the per-call response path: the response dispatcher delivers from a
/// synchronous callback and cannot apply backpressure, so a bounded channel
/// would turn a slow consumer into a **silent** loss.
pub fn unbounded_channel<T, E>() -> (Sender<T, E>, Observable<T, E>) {
    let (tx, rx) = async_channel::unbounded::<WireEvent<T, E>>();
    (
        Sender { inner: tx },
        Observable {
            inner: StreamInner::Transport { rx, pending: None },
            terminated: false,
        },
    )
}
