[package]
name = "ice-rpc-rx"
version.workspace = true
edition = "2021"
description = "Reactive operators (RxJS-like) for ice-rpc event streams"
license = "Apache-2.0"
publish = false

[features]
tokio = ["ice-rpc/tokio"]

[dependencies]
ice-rpc = { path = "../ice-rpc" }

[dev-dependencies]
pollster = "1.0"
tokio = { workspace = true }
async-trait = { workspace = true }
rkyv = { workspace = true }
serde = { workspace = true }
log = { workspace = true }

[[example]]
name = "state_service"
required-features = ["tokio"]
