//! The pull-based [`Observable`] — the concrete stream type returned by services.
//!
//! `Observable` is the push→pull boundary: it wraps either a local channel, an
//! inline buffer (`of`/`from`) or a boxed operator pipeline, and always presents
//! the same sequence of [`Event`]s. It knows nothing about the wire: framing and
//! serialization belong to the transport.

use std::pin::Pin;
use std::task::{Context, Poll};

use crate::error::RpcError;
use crate::{Event, ObservableError, Sender};

/// Action run when the transport stream of a call is dropped, told whether the
/// stream had delivered a terminal event.
///
/// The transport registers the release of its response handler here: an
/// abandoned call (`timeout`, `take_until`, a dropped stream) must not leave the
/// handler registered for the rest of the process lifetime.
///
/// The flag is what tells an **abandoned** call from an **answered** one, and it
/// is read where the answer is known for certain: the terminal travels through
/// this very stream, so the flag cannot race with the handler that published it.
/// The transport uses it to cancel a call remotely only when the caller really
/// stopped listening.
type Cleanup = Box<dyn FnOnce(bool) + Send>;

pin_project_lite::pin_project! {
    /// Internal storage backing an [`Observable`].
    ///
    /// Three sources: `Channel` (a local producer/consumer pair, the RPC response
    /// path), `Inline` (already-computed `of`/`from` events) and `Pipeline` (a
    /// boxed operator stream).
    #[project = StreamInnerProj]
    enum StreamInner<T, E> {
        Channel {
            #[pin]
            rx: async_channel::Receiver<Event<T, E>>,
            // Released with the stream, see `Observable::with_cleanup`.
            _cleanup: Option<Cleanup>,
        },
        Inline {
            // Single-consumer queue: read through `&mut self` (see `recv`).
            queue: std::collections::VecDeque<Event<T, E>>,
        },
        Pipeline {
            // Boxed so the wrapped stream need not be `Unpin`.
            stream: Pin<Box<dyn futures_lite::Stream<Item = Event<T, E>> + Send>>,
        },
    }
}

pin_project_lite::pin_project! {
    /// Consumer-side receiver of RPC events.
    ///
    /// The concrete type behind the public [`Observable`] name and the return
    /// type of every method generated by `#[service]`. Two pull-based styles:
    /// [`Observable::recv`] yields the full [`Event`] vocabulary, while
    /// [`Observable::next`] yields `Option<Result<T, ObservableError<E>>>`.
    ///
    /// Both observe the same sequence of `Next` values followed by a terminal
    /// event, whatever the source.
    ///
    /// An `Observable` is **single-subscription** (it does not implement
    /// `Clone`): use `Subject` to fan a stream out to several consumers.
    pub struct Observable<T, E> {
        #[pin]
        inner: StreamInner<T, E>,
        // Set as soon as a terminal event (`Complete` / `Error`) has been
        // delivered, so that a later channel close is reported as a normal end
        // (`None` from `next`) instead of an abrupt one.
        terminated: bool,
    }

    // Explicit rather than left to the drop of the field: the cleanup is the
    // release point of a call, so it must not depend on how the projection
    // macro destroys the pinned enum.
    impl<T, E> PinnedDrop for Observable<T, E> {
        fn drop(this: Pin<&mut Self>) {
            let this = this.project();
            // Read before the cleanup is taken: an answered call and an abandoned
            // one are not the same drop.
            let terminated = *this.terminated;
            if let StreamInnerProj::Channel { _cleanup, .. } = this.inner.project() {
                if let Some(action) = _cleanup.take() {
                    action(terminated);
                }
            }
        }
    }
}

impl<T, E> Observable<T, E> {
    /// Builds a pure, channel-free observable from an already-computed event
    /// list.
    ///
    /// Used by the `of`/`from` constructors and by
    /// [`Observable::from_technical_error`]. The events are stored in an inline
    /// `VecDeque`: a single allocation, no `Arc`, no mutex.
    #[doc(hidden)]
    pub fn from_events(events: impl IntoIterator<Item = Event<T, E>>) -> Self {
        Self {
            inner: StreamInner::Inline {
                queue: events.into_iter().collect(),
            },
            terminated: false,
        }
    }

    /// Builds an observable that only emits a terminal technical error.
    ///
    /// Used when an RPC call fails before the transport stream exists (service
    /// not found, provider unreachable, discovery timeout, ...).
    #[doc(hidden)]
    pub fn from_technical_error(err: RpcError) -> Self {
        Self::from_events([Event::Error(ObservableError::Technical(err))])
    }

    /// Builds an [`Observable`] from any stream of [`Event`].
    ///
    /// Makes **any** poll-based stream usable as the return value of a service
    /// method. The `CompleteWith` single-sample optimization is preserved: a
    /// `Next(v)` immediately followed by a `Complete` is folded into one sample.
    ///
    /// # Example
    /// ```rust,ignore
    /// async fn watch(&self, count: u32) -> Observable<u32, String> {
    ///     ice_rpc::from(1..=count).delay(Duration::from_millis(100))
    /// }
    /// ```
    #[doc(hidden)]
    pub fn from_stream<S>(stream: S) -> Self
    where
        S: futures_lite::Stream<Item = Event<T, E>> + Send + 'static,
        T: 'static,
        E: 'static,
    {
        Self {
            inner: StreamInner::Pipeline {
                stream: Box::pin(stream),
            },
            terminated: false,
        }
    }

    /// Attaches an action run when this observable is dropped.
    ///
    /// The transport uses it to release the response handler of a call, and to
    /// cancel the call remotely when nobody was listening anymore. The action
    /// receives **whether a terminal event had been delivered** through this
    /// stream: `true` means the call was answered, `false` that it was abandoned
    /// — an unread response, a `take_until` that fired, a `timeout` that elapsed.
    ///
    /// The action fires exactly when the **last** owner of the stream is dropped:
    /// every operator moves its source into its own wrapper, so a pipeline keeps
    /// the original observable alive and the cleanup runs with the pipeline, not
    /// with the intermediate steps.
    ///
    /// Ignored for an observable with no channel source, which has nothing to
    /// release.
    #[doc(hidden)]
    pub fn with_cleanup(mut self, cleanup: impl FnOnce(bool) + Send + 'static) -> Self {
        if let StreamInner::Channel { _cleanup, .. } = &mut self.inner {
            *_cleanup = Some(Box::new(cleanup));
        }
        self
    }

    /// Receives the next user-facing event — the full [`Event`] vocabulary.
    ///
    /// `Err(RecvError)` means the source closed: a normal end if a terminal event
    /// was already delivered, an abrupt close otherwise.
    ///
    /// Takes `&mut self` because an inline observable drains its queue without
    /// interior mutability.
    pub async fn recv(&mut self) -> Result<Event<T, E>, async_channel::RecvError> {
        let event = match &mut self.inner {
            StreamInner::Channel { rx, .. } => rx.recv().await,
            StreamInner::Inline { queue } => match queue.pop_front() {
                Some(event) => Ok(event),
                None => Err(async_channel::RecvError),
            },
            StreamInner::Pipeline { stream } => {
                match futures_lite::future::poll_fn(|cx| {
                    futures_lite::Stream::poll_next(stream.as_mut(), cx)
                })
                .await
                {
                    Some(event) => Ok(event),
                    None => Err(async_channel::RecvError),
                }
            }
        };

        if let Ok(delivered) = &event {
            if delivered.is_terminal() {
                self.terminated = true;
            }
        }
        event
    }

    /// Awaits the next emitted value: the concise view over
    /// [`Observable::recv`].
    ///
    /// - `Next(v)`  → `Some(Ok(v))`
    /// - `Error(e)` → `Some(Err(e))`
    /// - `Complete` → `None`
    ///
    /// `None` always means *the producer completed cleanly*: a source that
    /// closes without a terminal event is reported as a technical error first.
    pub async fn next(&mut self) -> Option<Result<T, ObservableError<E>>> {
        match self.recv().await {
            Ok(Event::Next(v)) => Some(Ok(v)),
            Ok(Event::Error(e)) => Some(Err(e)),
            Ok(Event::Complete) => None,
            Err(_) if self.terminated => None,
            Err(_) => {
                // Abrupt end: report it once, then treat the stream as over.
                self.terminated = true;
                Some(Err(ObservableError::Technical(RpcError::TransportError(
                    "stream closed before completion".to_string(),
                ))))
            }
        }
    }

    /// Awaits the first emitted value of the observable.
    ///
    /// `Next(v)` → `Ok(v)`, `Error(e)` → `Err(e)`,
    /// `Complete`/closed → `Err(ObservableError::Empty)`.
    ///
    /// Delegates to [`first_event`], the canonical terminal implementation.
    pub async fn first_value(self) -> Result<T, ObservableError<E>> {
        first_event(self).await
    }

    /// Awaits the **last** emitted value of the observable.
    ///
    /// `Next(v)`… `Complete` → `Ok(last)`, `Error(e)` → `Err(e)`, and
    /// `Err(ObservableError::Empty)` when the stream carries no value at all.
    ///
    /// Drains the stream instead of buffering it: one slot is held, not one
    /// value per event, so a long response costs the same as a short one. The
    /// counterpart of [`first_value`](Self::first_value); the canonical
    /// implementation lives in [`last_event`].
    ///
    /// # Example
    /// ```rust
    /// use ice_rpc_rx::{from, rt::block_on};
    ///
    /// let last = block_on(from::<i32, String, _>([1, 2, 3]).last_value())
    ///     .expect("the stream ends with a value");
    /// assert_eq!(last, 3);
    /// ```
    pub async fn last_value(self) -> Result<T, ObservableError<E>> {
        last_event(self).await
    }

    /// Collects every emitted value into a `Vec`.
    ///
    /// The observable is consumed until `Complete` (or until it is closed). On a
    /// terminal `Error` the collected values are discarded and the error is
    /// returned.
    ///
    /// Delegates to [`collect_values`], the canonical terminal implementation.
    pub async fn collect(self) -> Result<Vec<T>, ObservableError<E>> {
        collect_values(self).await
    }
}

/// Awaits the first event of any stream of [`Event`].
///
/// This is the **single** implementation behind [`Observable::first_value`];
/// living in a free function lets the generated code and the operators reuse it
/// on a raw `futures_lite::Stream`.
///
/// Reachable as `ice_rpc::gen::first_event`.
#[doc(hidden)]
pub async fn first_event<S, T, E>(stream: S) -> Result<T, ObservableError<E>>
where
    S: futures_lite::Stream<Item = Event<T, E>>,
{
    let mut stream = std::pin::pin!(stream);
    match futures_lite::future::poll_fn(|cx| futures_lite::Stream::poll_next(stream.as_mut(), cx))
        .await
    {
        Some(Event::Next(v)) => Ok(v),
        Some(Event::Error(e)) => Err(e),
        Some(Event::Complete) | None => Err(ObservableError::Empty),
    }
}

/// Awaits the last event of any stream of [`Event`].
///
/// This is the **single** implementation behind [`Observable::last_value`];
/// living in a free function lets the generated code and the operators reuse it
/// on a raw `futures_lite::Stream`.
///
/// Reachable as `ice_rpc::gen::last_event`.
#[doc(hidden)]
pub async fn last_event<S, T, E>(stream: S) -> Result<T, ObservableError<E>>
where
    S: futures_lite::Stream<Item = Event<T, E>>,
{
    let mut stream = std::pin::pin!(stream);
    let mut last = None;
    loop {
        match futures_lite::future::poll_fn(|cx| {
            futures_lite::Stream::poll_next(stream.as_mut(), cx)
        })
        .await
        {
            Some(Event::Next(v)) => last = Some(v),
            // A terminal error wins even when a value was already read: the
            // stream failed. `collect` behaves the same way — it discards what
            // it gathered — and returning the last value here would report a
            // failure as a success.
            Some(Event::Error(e)) => return Err(e),
            // `Empty` is the artefact for "ended carrying nothing", the same
            // answer `first_event` gives, so the two terminals stay symmetric.
            Some(Event::Complete) | None => return last.ok_or(ObservableError::Empty),
        }
    }
}

/// Collects every value of any stream of [`Event`].
///
/// The stream is drained until `Complete` (or until it is closed). On a terminal
/// `Error` the collected values are discarded and the error is returned.
///
/// This is the **single** implementation behind [`Observable::collect`].
///
/// Reachable as `ice_rpc::gen::collect_values`.
#[doc(hidden)]
pub async fn collect_values<S, T, E>(stream: S) -> Result<Vec<T>, ObservableError<E>>
where
    S: futures_lite::Stream<Item = Event<T, E>>,
{
    let mut stream = std::pin::pin!(stream);
    let mut values = Vec::new();
    while let Some(event) =
        futures_lite::future::poll_fn(|cx| futures_lite::Stream::poll_next(stream.as_mut(), cx))
            .await
    {
        match event {
            Event::Next(v) => values.push(v),
            Event::Complete => return Ok(values),
            Event::Error(e) => return Err(e),
        }
    }
    // Source closed without a terminal event: return what was collected.
    Ok(values)
}

impl<T, E> futures_lite::Stream for Observable<T, E> {
    type Item = Event<T, E>;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let this = self.project();
        let polled = match this.inner.project() {
            StreamInnerProj::Channel { rx, .. } => futures_lite::Stream::poll_next(rx, cx),
            StreamInnerProj::Inline { queue } => match queue.pop_front() {
                Some(event) => Poll::Ready(Some(event)),
                None => Poll::Ready(None),
            },
            StreamInnerProj::Pipeline { stream } => {
                futures_lite::Stream::poll_next(stream.as_mut(), cx)
            }
        };

        // Keep `terminated` in sync for callers that poll the stream directly
        // (`as_stream` pipelines, `Subject` relays) before falling back to
        // `recv` / `next`.
        if let Poll::Ready(Some(event)) = &polled {
            if event.is_terminal() {
                *this.terminated = true;
            }
        }
        polled
    }
}

/// Creates a bounded channel of RPC events.
///
/// Runtime-agnostic replacement for `tokio::sync::mpsc::channel`. This is the
/// local producer/consumer boundary: producers push [`Event`]s, the returned
/// [`Observable`] pulls them.
///
/// A capacity of 1 cannot carry [`Sender::send_complete_with`], which enqueues
/// two events: give a producer that closes a single value at least two slots.
pub fn channel<T, E>(capacity: usize) -> (Sender<T, E>, Observable<T, E>) {
    let (tx, rx) = async_channel::bounded::<Event<T, E>>(capacity);
    (
        Sender { inner: tx },
        Observable {
            inner: StreamInner::Channel { rx, _cleanup: None },
            terminated: false,
        },
    )
}

/// Creates an **unbounded** channel of RPC events.
///
/// Used for the per-call response path: the response dispatcher delivers from a
/// synchronous callback and cannot apply backpressure, so a bounded channel
/// would turn a slow consumer into a **silent** loss.
pub fn unbounded_channel<T, E>() -> (Sender<T, E>, Observable<T, E>) {
    let (tx, rx) = async_channel::unbounded::<Event<T, E>>();
    (
        Sender { inner: tx },
        Observable {
            inner: StreamInner::Channel { rx, _cleanup: None },
            terminated: false,
        },
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::Arc;

    /// A cleanup attached to a channel observable runs when it is dropped.
    #[test]
    fn dropping_a_channel_observable_runs_its_cleanup() {
        let ran = Arc::new(AtomicBool::new(false));
        let (_tx, rx) = unbounded_channel::<i32, String>();

        let flag = Arc::clone(&ran);
        let observable = rx.with_cleanup(move |_terminated| flag.store(true, Ordering::Relaxed));
        match &observable.inner {
            StreamInner::Channel { _cleanup, .. } => {
                assert!(_cleanup.is_some(), "with_cleanup must attach the action");
            }
            _ => panic!("expected a channel observable"),
        }
        assert!(!ran.load(Ordering::Relaxed), "the cleanup runs on drop");

        drop(observable);
        assert!(ran.load(Ordering::Relaxed));
    }

    /// An operator moves its source into its own wrapper, so the cleanup must
    /// survive the whole pipeline: it fires with the pipeline, not with the
    /// intermediate observable that built it.
    #[test]
    fn a_pipeline_keeps_the_cleanup_until_it_is_dropped() {
        let ran = Arc::new(AtomicBool::new(false));
        let (_tx, rx) = unbounded_channel::<i32, String>();

        let flag = Arc::clone(&ran);
        let pipeline = rx
            .with_cleanup(move |_terminated| flag.store(true, Ordering::Relaxed))
            .map(|value| value * 2)
            .filter(|value| *value > 0);
        assert!(
            !ran.load(Ordering::Relaxed),
            "the source is still owned by the pipeline"
        );

        drop(pipeline);
        assert!(ran.load(Ordering::Relaxed));
    }

    /// An abandoned call and an answered one are not the same drop: the cleanup
    /// is told which one it is, from the one place that cannot race — the stream
    /// the terminal travelled through.
    #[test]
    fn the_cleanup_is_told_whether_the_stream_terminated() {
        // Abandoned: nothing was ever read, so no terminal was delivered.
        let abandoned = Arc::new(AtomicBool::new(true));
        let (_tx, rx) = unbounded_channel::<i32, String>();
        let flag = Arc::clone(&abandoned);
        drop(rx.with_cleanup(move |terminated| flag.store(terminated, Ordering::Relaxed)));
        assert!(
            !abandoned.load(Ordering::Relaxed),
            "a stream nobody read was never answered"
        );

        // Answered: the terminal went through the observable.
        let answered = Arc::new(AtomicBool::new(false));
        let (tx, rx) = unbounded_channel::<i32, String>();
        let flag = Arc::clone(&answered);
        let mut observable =
            rx.with_cleanup(move |terminated| flag.store(terminated, Ordering::Relaxed));
        tx.try_send_event(Event::Complete)
            .expect("the channel is unbounded");
        assert!(matches!(
            crate::rt::block_on(observable.recv()),
            Ok(Event::Complete)
        ));

        drop(observable);
        assert!(
            answered.load(Ordering::Relaxed),
            "the call was answered before the drop"
        );
    }

    /// Keeps the last value of a finite stream.
    #[test]
    fn last_value_keeps_the_final_value() {
        let last = crate::rt::block_on(crate::from::<i32, String, _>([1, 2, 3]).last_value());

        assert_eq!(last.expect("the stream ends with a value"), 3);
    }

    /// A stream that carries no value at all reports `Empty`, exactly like
    /// `first_value` — and it **returns**: `None` must end the read, never send
    /// the loop round again.
    #[test]
    fn last_value_is_empty_without_any_value() {
        let last = crate::rt::block_on(crate::from::<i32, String, _>([]).last_value());

        assert!(matches!(last, Err(ObservableError::Empty)));
    }

    /// The realistic trigger of the same case: a pipeline that dropped every
    /// value ends on its exhausted source and must still return.
    #[test]
    fn last_value_is_empty_when_a_pipeline_dropped_everything() {
        let last = crate::rt::block_on(
            crate::from::<i32, String, _>([1, 2, 3])
                .filter(|_| false)
                .last_value(),
        );

        assert!(matches!(last, Err(ObservableError::Empty)));
    }

    /// An error raised **after** values is not swallowed: returning the last
    /// value would report a failed stream as a successful one.
    #[test]
    fn last_value_forwards_an_error_raised_after_values() {
        let stream = Observable::from_events([
            Event::Next(1),
            Event::Next(2),
            Event::Error(ObservableError::Business("boom".to_owned())),
        ]);

        let last = crate::rt::block_on(stream.last_value());

        assert!(matches!(last, Err(ObservableError::Business(e)) if e == "boom"));
    }

    /// A technical error terminates the stream the same way, values or not.
    #[test]
    fn last_value_forwards_a_technical_error() {
        let stream = Observable::<i32, String>::from_technical_error(RpcError::Timeout);

        let last = crate::rt::block_on(stream.last_value());

        assert!(matches!(
            last,
            Err(ObservableError::Technical(RpcError::Timeout))
        ));
    }

    /// A channel source is the path a real response takes: the read must work
    /// through the queue and not only through the inline shortcut.
    #[test]
    fn last_value_reads_through_a_channel_source() {
        let (tx, rx) = unbounded_channel::<i32, String>();

        tx.try_send_event(Event::Next(1)).expect("unbounded");
        tx.try_send_event(Event::Next(2)).expect("unbounded");
        tx.try_send_event(Event::Complete).expect("unbounded");
        drop(tx);

        let last = crate::rt::block_on(rx.last_value());

        assert_eq!(last.expect("the stream ends with a value"), 2);
    }

    /// A source that closes without a terminal is read like a `Complete`, which
    /// is the answer `first_event` gives: the two terminals stay symmetric.
    #[test]
    fn last_value_treats_an_abrupt_close_like_a_completion() {
        let (tx, rx) = unbounded_channel::<i32, String>();

        tx.try_send_event(Event::Next(7)).expect("unbounded");
        drop(tx);

        let last = crate::rt::block_on(rx.last_value());

        assert_eq!(last.expect("the value read before the close is kept"), 7);
    }
}
